Core upgrade phase 1 (#4342)
* chore: catch up ra/upgrade_v3_test1 with develop

* chore: fix a lot of soql int tests

* fix: fix sObjectDescribe.test before each

* chore: fix authInfo tests

* chore: remove only and lint fixes

* chore: fix forceAuthAccessTokenLogin test

* chore: ongoing test fixes

* chore: remove onlys

* chore: fix orgList Tests

* chore: fix completion tests

* chore: fix completion tests

* chore: fix chai syntax for authInfo test

* chore: set resource class for circle jobs

* chore: fix circle size config

* chore: play with circle config to see if it improves speed

* chore: remove packaging entry added to package.json

* chore: Enable default org to display in status bar and org list to show in Org Picker with core v3 updates (#4290)

* chore: use keys for default org and dev hub from core v3

* chore: point to the .sfdx root folder, where auth files are located

* chore: use key from core v3

* refactor: correct casing of var name

* Revert "chore: use key from core v3"

This reverts commit 2bfc6d2a0c60b6917953314eaca4f015dc94a66c.

* fix: feedback-changes-for-update_v3_test1 (#4302)

* fix: remove unnecessary configs (#4303)

* fix: cleanup auth and login from v3 first pass (#4309)

* fix: review cleanup (#4311)

* refactor: revert back to backwards compatible sfdx config for now

with follow up work to use config aggregator and core v3 apis

* refactor: orgUtil commented out temporarily to test build

rolling back some of the changes on the core v3 branch to see a smaller build

* refactor: orgUtil commented out temporarily to test build

rolling back some of the changes on the core v3 branch to see a smaller build

* chore: fix failing test - use sfdx

* chore: rollback chg to fix tests

* chore: rollback to use sfdx and old key

* fix: update for checkForExpiredOrgs() to use OrgAuthorization (#4341)

* fix: update for checkForExpiredOrgs() to use OrgAuthorization

* chore: saved file to run formatter

To get past CircleCI build error:
ERROR: C:/Users/circleci/project/packages/salesforcedx-utils-vscode/src/helpers/utils.ts[26, 1]:
space indentation expected
ERROR: C:/Users/circleci/project/packages/salesforcedx-utils-vscode/src/helpers/utils.ts[28, 1]:
space indentation expected

* fix: moved getAuthFieldsFor() and getDefaultDevHubUsernameorAlias() from orgList to orgUtil

* fix: moved getAuthFieldsFor() and getDefaultDevHubUsernameorAlias() from orgList to orgUtil

* fix: moved getAuthFieldsFor() and getDefaultDevHubUsernameorAlias() from orgList to orgUtil

* fix: converted call to filter() and map() to just a for() loop

* fix: updated asyncFilter() to typed callback

* fix: updated asyncFilter() to typed callback

* fix: updated asyncFilter() to typed callback

Co-authored-by: Kenneth Lewis <kenneth.lewis@salesforce.com>

* chore: fix orgList tests after merge

* chore: clean up

* chore: fixup orgUtil after cherry pick

* chore: remove deprecated type

* chore: update comment

* refactor: use getInstance over create

* test: update forceAuthAccessTokenLogin test for corev3 changes (#4350)

* fix: fixed manifest builder error (#4352)

* refactor: use org api version if no user config (#4348)

* refactor: use org api version if no user config

* refactor: await the setting of the api version

* refactor: first test update

* refactor: update tests and move utility fns

* chore: remove comment

* refactor: fix failing test

No need to call await here

* chore: fix linter issues

* refactor: update tests add expects

* refactor: make fn easy to grok and debug

* refactor: update import and dont notify

if default username is not set

* refactor: get around linter error

Error was: Promises must be handled appropriately

* refactor: use await

* refactor: dont create authInfo if no default usrnm

* refactor: only get api version from org if needed

Co-authored-by: Gordon Bockus <gbockus@salesforce.com>
Co-authored-by: jbeeghly <46358907+jeffb-sfdc@users.noreply.github.com>
Co-authored-by: Ritam Agrawal <72183558+RitamAgrawal@users.noreply.github.com>
Co-authored-by: Randi Wilson <randi274@gmail.com>
Co-authored-by: angela-young <60243824+angela-young@users.noreply.github.com>
Co-authored-by: Ritam Agrawal <ritam.kumari.27@gmail.com>
Co-authored-by: gbockus-sf <76090802+gbockus-sf@users.noreply.github.com>